// quotes-app/fe-angular/src/app/page-heading/page-heading.component.ts
import { Component, OnInit } from '@angular/core';
import { auth } from '../shared/authHelper';

@Component({
  selector: 'app-page-heading',
  templateUrl: './page-heading.component.html',
  styleUrls: ['./page-heading.component.css'],
})
export class PageHeadingComponent implements OnInit {
  isLoggedIn = auth.isLoggedIn();

  constructor() {}

  ngOnInit(): void {}
}

<div *ngIf="!isLoggedIn">
  <div class="container">
    <div class="row m-2">
      <div class="col-sm-8">
        <h5 class="logo">QuotesApp</h5>
      </div>
      <div class="col-sm-4">
        <app-signup></app-signup>
        <app-signin></app-signin>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="jumbotron">
      <div class="content">
        <h2 class="jumbotron-heading">QuotesApp</h2>
        <p class="jumbotron-content">A place to share your favourite quotes.</p>
      </div>
    </div>
  </div>
</div>

<div *ngIf="isLoggedIn" class="container">
  <div class="row m-2">
    <div class="col-sm-8">
      <h5 class="logo">QuotesApp</h5>
    </div>
    <div class="col-sm-4">
      <app-new-quote-modal></app-new-quote-modal>
      <app-user-menu></app-user-menu>
    </div>
  </div>
</div>

// quotes-app/fe-ts-react/src/components/pageHeading/pageHeading.tsx
import "./pageHeading.css";
import React, { useContext } from "react";
import { Col, Container, Row } from "react-bootstrap";
import SignUp from "../modals/signUp";
import SignIn from "../modals/signIn";
import LogOut from "../logOut/logOut";
import { NewQuote } from "../modals/newQuotes";
import UserMenu from "../userMenu/userMenu";
import { QuotesContext } from "../../App";

const pageHeadingBeforeLogin = (setLogIn: () => void) => {
	return (
		<>
			<Container>
				<Row className="m-2">
					<Col sm={8}>
						<h5 className="logo">QuotesApp</h5>
					</Col>
					<Col>
						<SignUp />
						<SignIn setLogIn={setLogIn} />
					</Col>
				</Row>
			</Container>
			<Container fluid>
				<div className="jumbotron">
					<div className="content">
						<h2 className="jumbotron-heading">QuotesApp</h2>
						<p className="jumbotron-content">
							A place to share your favourite quotes.
						</p>
					</div>
				</div>
			</Container>
		</>
	);
};

const pageHeadingAfterLogin = () => {
	return (
		<Container>
			<Row className="m-2">
				<Col sm={8}>
					<h5 className="logo">QuotesApp</h5>
				</Col>
				<Col>
					<NewQuote />
					<UserMenu />
				</Col>
			</Row>
		</Container>
	);
};

const PageHeading = () => {
	const contextValue = useContext(QuotesContext);

	return (
		<>
			{contextValue.isLoggedIn
				? pageHeadingAfterLogin()
				: pageHeadingBeforeLogin(contextValue.logIn)}
		</>
	);
};

export default PageHeading;
