// quotes-app/fe-js-react/src/components/modals/editQuote.jsx
import React, { useEffect, useState } from "react";
import { Modal, Button, Form, Input } from "antd";
import TextArea from "antd/lib/input/TextArea";
import { editQuote } from "../../apis/protectedRoutes";
import { helpers } from "../../utils/generalHelpers";

const swalProps = {
	title: "Are you sure you want to Edit?",
	icon: "info",
	confirmButtonText: "Yes, edit it!",
};

export const EditModal = (props) => {
	const [form] = Form.useForm();

	const handleOk = () => {
		props.handleEditModalCancel();
	};

	const handleCancel = () => {
		props.handleEditModalCancel();
	};

	const onFinish = async (values) => {
		let result = await helpers.getConfirmAlert({ ...swalProps });
		if (result.isConfirmed) {
			await editQuote(values);
			props.handleEditModalCancel();
		}
	};

	const onReset = () => {
		form.resetFields();
	};

	useEffect(() => {
		form.setFieldsValue({
			id: props.data.id,
			quote: props.data.quote,
			author: props.data.author,
		});
	});

	return (
		<>
			<Modal
				title="Edit Quote"
				visible={props.isEditModalVisible}
				onOk={handleOk}
				onCancel={handleCancel}
				footer={null}
				width={"50%"}
			>
				<Form form={form} name="control-hooks" onFinish={onFinish}>
					<Form.Item name="id" style={{ display: "none" }}></Form.Item>
					<Form.Item
						name="quote"
						label="Quote"
						rules={[
							{
								required: true,
							},
						]}
					>
						<TextArea autoSize />
					</Form.Item>
					<Form.Item
						name="author"
						label="Author"
						rules={[
							{
								required: true,
							},
						]}
					>
						<Input />
					</Form.Item>
					<Form.Item>
						<Button type="primary" htmlType="submit">
							Submit
						</Button>
						<Button htmlType="button" onClick={onReset}>
							Reset
						</Button>
					</Form.Item>
				</Form>
			</Modal>
		</>
	);
};

// quotes-app/fe-vue/src/components/UserDetails/ModalPopup/EditQuote.vue
<template>
  <img
    src="../../../assets/edit.png"
    id="card-icons"
    alt="logo"
    @click="dialog = true"
  />
  <v-dialog v-model="dialog" width="30%">
    <v-card>
      <v-card-title>
        <span class="text-h5">Edit Quote</span>
      </v-card-title>
      <Form
        as="v-form"
        :validation-schema="schema"
        @submit="onSubmit"
        style="width: 85%; margin: auto"
      >
        <TextAreaFieldWithValidation
          name="quote"
          label="Quote"
          type="String"
          :quote="quote"
        />

        <TextFieldWithValidation
          name="author"
          label="Author"
          type="String"
          :author="author"
        />

        <v-card-actions style="float: right">
          <v-btn color="primary" @click="dialog = false">Close</v-btn>
          <v-btn color="primary" type="submit"> Edit </v-btn>
        </v-card-actions>
      </Form>
    </v-card>
  </v-dialog>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Form } from "vee-validate";
import * as yup from "yup";
import TextFieldWithValidation from "@/components/CommonComp/TextFieldWithValidation.vue";
import TextAreaFieldWithValidation from "@/components/CommonComp/TextAreaFieldWithValidation.vue";
import { helpers } from "@/utils/generalHelpers";
import { editQuote } from "@/apis/protectedRoutes";
import { useUserStore } from "@/stores/userStore";

export default defineComponent({
  name: "EditQuote",
  props: {
    quoteId: {
      type: String,
      requird: true,
    },
    quote: {
      type: String,
      requird: true,
    },
    author: {
      type: String,
      requird: true,
    },
    tags: {
      type: String,
      requird: true,
    },
  },
  components: {
    Form,
    TextFieldWithValidation,
    TextAreaFieldWithValidation,
  },
  data() {
    return {
      dialog: false,
      valid: false,
      schema: yup.object({
        quote: yup.string().required().min(4),
        author: yup.string().required(),
      }),
    };
  },
  methods: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async onSubmit(values: any) {
      const result = await helpers.getConfirmAlert({
        title: "Are you sure you want to Edit?",
        icon: "info",
        confirmButtonText: "Yes, edit it!",
      });
      if (result.isConfirmed) {
        values.id = this.quoteId;
        values.tags = this.tags;

        await editQuote(values);
        const userStore = useUserStore();
        userStore.fetchQuotes();
        this.dialog = false;
      }
    },
  },
});
</script>
