// quotes-app/fe-ts-react/src/components/userSettings/userSettings.tsx
import React, { useEffect, useState } from "react";
import { Modal, Button, Form, Input } from "antd";
import { getUserDetails, updateUser } from "../../apis/protectedRoutes";
import { formItemLayout } from "../../utils/formHelper";
import { SettingOutlined } from "@ant-design/icons";
import { helpers } from "../../utils/generalHelpers";

interface UserData {
	created_at?: string;
	email?: string;
	id?: string;
	password?: string;
	userName?: string;
}

interface UpdateUser {
	email: string;
	password: string;
	userName: string;
}

const swalProps = {
	title: "Are you sure you want to update your details?",
	icon: "info",
	confirmButtonText: "Yes, update it!",
};

const UserSettings = () => {
	const [form] = Form.useForm();
	const [isModalVisible, setIsModalVisible] = useState(false);
	const [userData, setUserData] = useState<UserData>({});

	useEffect(() => {
		fetchInitial();
	}, [isModalVisible]);

	useEffect(() => {
		form.setFieldsValue({
			userName: userData.userName,
			email: userData.email,
		});
	}, [userData, form]);

	const fetchInitial = async () => {
		const userDetails = await getUserDetails();
		setUserData(userDetails);
	};

	const showModal = () => {
		setIsModalVisible(true);
	};

	const handleOk = () => {
		setIsModalVisible(false);
	};

	const handleCancel = () => {
		setIsModalVisible(false);
	};

	const onFinish = async (values: UpdateUser) => {
		let result = await helpers.getConfirmAlert({ ...swalProps });
		if (result.isConfirmed) {
			if (values.password === undefined) {
				const { password, ...result } = values;
				await updateUser(result);
			} else {
				await updateUser(values);
			}
			setIsModalVisible(false);
		}
	};

	const onReset = () => {
		form.resetFields();
	};

	return (
		<>
			<a
				style={{ margin: 20, marginLeft: "3%" }}
				type="primary"
				onClick={showModal}
			>
				<SettingOutlined />
				Settings
			</a>
			<Modal
				title="User Settings"
				visible={isModalVisible}
				onOk={handleOk}
				onCancel={handleCancel}
				footer={null}
			>
				<Form
					{...formItemLayout}
					form={form}
					name="control-hooks"
					onFinish={onFinish}
				>
					<Form.Item
						name="userName"
						label="Username"
						rules={[
							{
								required: true,
							},
						]}
					>
						<Input />
					</Form.Item>
					<Form.Item
						name="email"
						label="Email"
						rules={[
							{
								required: true,
							},
						]}
					>
						<Input />
					</Form.Item>
					<Form.Item name="password" label="Password">
						<Input placeholder="New Password" />
					</Form.Item>
					<Form.Item>
						<Button type="primary" htmlType="submit">
							Update
						</Button>
						<Button htmlType="button" onClick={onReset}>
							Reset
						</Button>
					</Form.Item>
				</Form>
			</Modal>
		</>
	);
};

export default UserSettings;

// quotes-app/fe-vue/src/components/UserDetails/ModalPopup/UserSettings.vue
<template>
  <button-custom @click="dialog = true">
    <img
      src="../../../assets/settings.png"
      id="image-icons"
      alt="settings-img"
    />
    Settings
  </button-custom>
  <v-dialog v-model="dialog" width="30%">
    <v-card>
      <v-card-title>
        <span class="text-h5">Settings</span>
      </v-card-title>
      <Form
        as="v-form"
        :validation-schema="schema"
        @submit="onSubmit"
        style="width: 85%; margin: auto"
      >
        <!-- <Field name="name" type="text" v-slot="{ field, errors }">
          <v-text-field
            v-bind="field"
            label="Username"
            :error-messages="errors"
            :value="userDetails.userName"
          />
        </Field>

      <TextFieldWithValidation
          name="email"
          label="Email"
          type="email"
          :email="userDetails.email"
        /> -->

        <TextFieldWithValidation
          name="name"
          label="User Name"
          type="String"
          :userName="userName"
        />

        <TextFieldWithValidation
          name="password"
          label="New Password"
          type="password"
        />

        <TextFieldWithValidation
          name="passwordConfirm"
          label="Confirm Password"
          type="password"
        />

        <v-card-actions style="float: right">
          <v-btn color="primary" @click="dialog = false">Close</v-btn>
          <v-btn color="primary" type="submit"> Create </v-btn>
        </v-card-actions>
      </Form>
    </v-card>
  </v-dialog>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { Form } from "vee-validate";
import * as yup from "yup";
import TextFieldWithValidation from "@/components/CommonComp/TextFieldWithValidation.vue";
import { helpers } from "@/utils/generalHelpers";
import { auth } from "@/utils/authHelpers";
import { getUserDetails, updateUser } from "@/apis/protectedRoutes";

export default defineComponent({
  name: "UserSettings",
  components: {
    Form,
    TextFieldWithValidation,
  },
  data() {
    return {
      dialog: false,
      valid: false,
      email: "",
      schema: yup.object({
        name: yup.string().required(),
        password: yup.string().min(6).required(),
        passwordConfirm: yup
          .string()
          .oneOf([yup.ref("password")], "Passwords must match")
          .required()
          .label("Password confirmation"),
      }),
    };
  },
  computed: {
    userName() {
      return auth.getUsername() ?? "";
    },
  },
  methods: {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    async onSubmit(values: any) {
      const payload = {
        userName: values.name,
        email: this.email,
        password: values.password,
      };
      const result = await helpers.getConfirmAlert({
        title: "Are you sure you want to update your details?",
        icon: "info",
        confirmButtonText: "Yes, update it!",
      });

      if (result.isConfirmed) {
        await updateUser(payload);

        sessionStorage.setItem("username", payload.userName);
        // const userStore = useUserStore();
        // userStore.loginUser(userData);
        this.$emit("onUserNameUpdate");
        this.dialog = false;
      }
    },
    async fetchUserDetails() {
      const userDetails = await getUserDetails();
      if (userDetails.id) {
        this.email = userDetails.email;
      }
    },
  },
  created() {
    this.fetchUserDetails();
  },
});
</script>
