// quotes-app/fe-ts-react/src/components/userHeading/userHeading.tsx
import "./userHeading.css";
import React, { useContext } from "react";
import { Col, Container, Row } from "react-bootstrap";
import { auth } from "../../utils/authHelpers";
import HomePage from "../homePage/homePage";
import UserSettings from "../userSettings/userSettings";
import { QuotesContext } from "../../App";
import LogOut from "../logOut/logOut";

const UserHeading = () => {
	const contextValue = useContext(QuotesContext);
	return (
		<>
			<Container>
				<Row className="m-2">
					<Col sm={8}>
						<h5 className="logo">QuotesApp</h5>
					</Col>
					<Col>
						<HomePage />
						<UserSettings />
						<LogOut setLogOut={contextValue.logOut} />
					</Col>
				</Row>
			</Container>
			<Container fluid>
				<div className="user-jumbotron">
					<div className="user-content">
						<img
							src={"https://api.realworld.io/images/smiley-cyrus.jpeg"}
							className="user-img"
							alt="user-img"
						/>

						<h5 className="user-jumbotron-content">{auth.getUsername()}</h5>
					</div>
				</div>
			</Container>
		</>
	);
};

export default UserHeading;

// quotes-app/fe-angular/src/app/user-heading/user-heading.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { auth } from '../shared/authHelper';

@Component({
  selector: 'app-user-heading',
  templateUrl: './user-heading.component.html',
  styleUrls: ['./user-heading.component.css'],
})
export class UserHeadingComponent implements OnInit {
  username = auth.getUsername();
  constructor(private router: Router) {}

  ngOnInit(): void {}

  logOut() {
    auth.clearSession();
    this.router.navigate(['/']);
  }

  goToHome() {
    this.router.navigate(['/']);
  }
}

<div class="container">
  <div class="row m-2">
    <div class="col-sm-8">
      <h5 class="logo">QuotesApp</h5>
    </div>
    <div class="col-sm-4">
      <a
        style="margin: 20; margin-left: 3%"
        type="primary"
        role="button"
        (click)="goToHome()"
      >
        Home
      </a>
      <app-user-settings></app-user-settings>
      <a
        style="margin: 20; margin-left: 3%"
        type="primary"
        role="button"
        (click)="logOut()"
      >
        Log out
      </a>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="user-jumbotron">
    <div class="user-content">
      <img
        src="https://api.realworld.io/images/smiley-cyrus.jpeg"
        class="user-img"
        alt="user-img"
      />

      <h5 class="user-jumbotron-content">{{ username }}</h5>
    </div>
  </div>
</div>
