// quotes-app/fe-angular/src/app/user-menu/user-menu.component.ts
import { Component, OnInit } from '@angular/core';
import { auth } from '../shared/authHelper';

@Component({
  selector: 'app-user-menu',
  templateUrl: './user-menu.component.html',
  styleUrls: ['./user-menu.component.css'],
})
export class UserMenuComponent implements OnInit {
  username = auth.getUsername();
  constructor() {}

  ngOnInit(): void {}
}

<a
  type="primary"
  href="/userdetails"
  class="anchor"
  style="margin: 20; margin-left: 3%"
>
  <img
    src="https://api.realworld.io/images/smiley-cyrus.jpeg"
    class="user-pic"
    alt="user-pic"
  />
  {{ username }}
</a>

// quotes-app/fe-ts-react/src/components/userMenu/userMenu.tsx
import "./userMenu.css";
import { auth } from "../../utils/authHelpers";

const UserMenu = () => {
	return (
		<a
			style={{ margin: 20, marginLeft: "3%" }}
			type="primary"
			href="/userdetails"
			className="anchor"
		>
			<img
				src={"https://api.realworld.io/images/smiley-cyrus.jpeg"}
				className="user-pic"
				alt="user-pic"
			/>
			{auth.getUsername()}
		</a>
	);
};

export default UserMenu;
