// quotes-app/fe-js-react/src/components/cardItem/cardItem.jsx
import "./cardItem.css";
import { Card, Tooltip } from "antd";
import Moment from "react-moment";
import {
	EditTwoTone,
	LikeTwoTone,
	DislikeTwoTone,
	DeleteTwoTone,
} from "@ant-design/icons";
import { useEffect, useState } from "react";
import Avatar from "antd/lib/avatar/avatar";
import { auth } from "../../utils/authHelpers";
import {
	deleteQuote,
	dislikeDown,
	dislikeUp,
	likeDown,
	likeUp,
} from "../../apis/protectedRoutes";
import { EditModal } from "../modals/editQuote";
import { helpers } from "../../utils/generalHelpers";

const swalProps = {
	title: "Are you sure you want to delete this quote ?",
	icon: "info",
	confirmButtonText: "Yes, delete it!",
};

const { Meta } = Card;

export const CardItem = (props) => {
	const [isEditModalVisible, setIsEditModalVisible] = useState(false);
	const [editModalData, setEditModalData] = useState({});
	const [isLoggerIn, setIsLoggerIn] = useState(auth.isLoggedIn());
	const [isLiked, setIsLiked] = useState(false);
	const [isDisliked, setIsDisliked] = useState(false);
	const [likeCount, setLikeCount] = useState(props.item.likes);
	const [dislikeCount, setDislikeCount] = useState(props.item.dislikes);

	useEffect(() => {
		if (props.isLiked) setIsLiked(true);

		if (props.isDisliked) setIsDisliked(true);
	}, [props]);

	const onClickEdit = (item) => {
		setEditModalData(item);
		setIsEditModalVisible(true);
	};

	const handleEditModalCancel = () => {
		setIsEditModalVisible(false);
		props.fetchMyQuotes();
	};

	const onClickDelete = async (id) => {
		let result = await helpers.getConfirmAlert({ ...swalProps });
		if (result.isConfirmed) {
			await deleteQuote(id);
			props.fetchMyQuotes();
		}
	};

	const onClickLike = async (id) => {
		if (isLiked) {
			await likeDown(id);
			setIsLiked(false);
			setLikeCount(likeCount - 1);
		} else {
			await likeUp(id);
			setIsLiked(true);
			setLikeCount(likeCount + 1);
		}

		if (isDisliked) {
			setIsDisliked(false);
			setDislikeCount(dislikeCount - 1);
		}
	};

	const onClickDislike = async (id) => {
		if (isDisliked) {
			await dislikeDown(id);
			setIsDisliked(false);
			setDislikeCount(dislikeCount - 1);
		} else {
			await dislikeUp(id);
			setIsDisliked(true);
			setDislikeCount(dislikeCount + 1);
		}

		if (isLiked) {
			setIsLiked(false);
			setLikeCount(likeCount - 1);
		}
	};

	const getLikeIcon = () => {
		return (
			<>
				{isLiked ? (
					<img
						src={"/like-filled.png"}
						id="image-icons"
						alt="logo"
						onClick={() => onClickLike(props.item.id)}
					/>
				) : (
					<img
						src={"/like-unfilled.jpg"}
						id="image-icons"
						alt="logo"
						onClick={() => onClickLike(props.item.id)}
					/>
				)}
			</>
		);
	};

	const getDislikeIcon = () => {
		return (
			<>
				{isDisliked ? (
					<img
						src={"/like-filled.png"}
						id="image-icons"
						className="dislike-image"
						alt="logo"
						onClick={() => onClickDislike(props.item.id)}
					/>
				) : (
					<img
						src={"/like-unfilled.jpg"}
						id="image-icons"
						className="dislike-image"
						alt="logo"
						onClick={() => onClickDislike(props.item.id)}
					/>
				)}
			</>
		);
	};

	const getActions = () => {
		const actions = [];

		actions.push(
			<div>
				<div className="like-dislike-value">
					{getLikeIcon()} {likeCount}
				</div>
			</div>,
			<div>
				<div className="like-dislike-value">
					{getDislikeIcon()} {dislikeCount}
				</div>
			</div>
		);

		if (props.myQuotes)
			actions.push(
				<div>
					<Tooltip title="Edit">
						<EditTwoTone
							className="icons"
							twoToneColor="#413939"
							key="edit"
							onClick={() => onClickEdit(props.item)}
						/>
					</Tooltip>
				</div>,
				<div>
					<Tooltip title="Delete">
						<DeleteTwoTone
							className="icons"
							twoToneColor="#eb2f96"
							onClick={() => onClickDelete(props.item.id)}
						/>
					</Tooltip>
				</div>
			);

		return actions;
	};

	return (
		<div className="card-container">
			{isEditModalVisible && (
				<EditModal
					isEditModalVisible={isEditModalVisible}
					handleEditModalCancel={handleEditModalCancel}
					data={editModalData}
				/>
			)}
			<Card
				key={props.item.id}
				loading={props.loading}
				hoverable={true}
				bordered={true}
				// style={{
				// 	backgroundColor: "#c59ec0",
				// }}
				// bodyStyle={{
				// 	textAlign: "center",
				// 	// wordWrap: "break-word",
				// 	whiteSpace: "pre-line",
				// }}
				actions={isLoggerIn && getActions()}
			>
				<div className="card-heading">
					<Avatar src="https://joeschmoe.io/api/v1/random" />
					<div className="info">
						<p className="creator"> {props.item.user.userName}</p>
						<Moment className="moment-date" format="dddd, MMMM Do YYYY">
							{props.item.created_at}
						</Moment>
					</div>
				</div>
				<Meta
					title={'"' + props.item.quote + '"'}
					description={props.item.author}
					style={{ textAlign: "center", whiteSpace: "pre-line" }}
				/>
				<ul className="tag-list">
					{props.item.tags.split(",").map((tag, index) => (
						<li key={index}>{tag}</li>
					))}
				</ul>
			</Card>
		</div>
	);
};

// quotes-app/fe-angular/src/app/card-item/card-item.component.ts
import { Component, Input, OnChanges, OnInit } from '@angular/core';
import { Subject, takeUntil } from 'rxjs';
import { auth } from '../shared/authHelper';
import { QuoteService } from '../shared/quotes.service';

@Component({
  selector: 'app-card-item',
  templateUrl: './card-item.component.html',
  styleUrls: ['./card-item.component.css'],
})
export class CardItemComponent implements OnInit, OnChanges {
  @Input() quoteItem: any = {};
  @Input() isLiked = false;
  @Input() isDisliked = false;
  likeCount = 0;
  dislikeCount = 0;
  isLike = this.isLiked;
  isDislike = this.isDisliked;

  isLoggedIn = auth.isLoggedIn();
  tags: any = [];
  likeImgSrc = 'assets/icons/like-unfilled.jpg';
  disLikeImgSrc = 'assets/icons/like-unfilled.jpg';
  errorMessage = '';

  private notifier = new Subject<void>();

  constructor(private quoteService: QuoteService) {}

  ngOnInit(): void {
    this.cleanTags();
  }

  ngOnChanges(): void {
    this.setImgSrc();
    this.likeCount = this.quoteItem.likes;
    this.dislikeCount = this.quoteItem.dislikes;
  }

  ngOnDestroy(): void {
    this.notifier.next();
    this.notifier.complete();
  }

  setImgSrc() {
    this.likeImgSrc = this.isLiked
      ? 'assets/icons/like-filled.png'
      : 'assets/icons/like-unfilled.jpg';

    this.disLikeImgSrc = this.isDisliked
      ? 'assets/icons/like-filled.png'
      : 'assets/icons/like-unfilled.jpg';
  }

  cleanTags() {
    this.quoteItem.tags.split(',').map((tag: string) => this.tags.push(tag));
  }

  onClickLike = async (id: string) => {
    if (this.isLiked) {
      await this.quoteService
        .likeDown(id)
        .pipe(takeUntil(this.notifier))
        .subscribe({
          next: (response) => {
            // console.log(response);
          },
          error: (err) => (this.errorMessage = err),
        });

      this.isLiked = false;
      this.likeCount = this.likeCount - 1;
    } else {
      await this.quoteService
        .likeUp(id)
        .pipe(takeUntil(this.notifier))
        .subscribe({
          next: (response) => {
            console.log(response);
          },
          error: (err) => (this.errorMessage = err),
        });

      this.isLiked = true;
      this.likeCount = this.likeCount + 1;
    }

    if (this.isDisliked) {
      this.isDisliked = false;
      this.dislikeCount = this.dislikeCount - 1;
    }

    this.setImgSrc();
  };

  onClickDislike = async (id: string) => {
    if (this.isDisliked) {
      await this.quoteService
        .dislikeDown(id)
        .pipe(takeUntil(this.notifier))
        .subscribe({
          next: (response) => {
            // console.log(response);
          },
          error: (err) => (this.errorMessage = err),
        });

      this.isDisliked = false;
      this.dislikeCount = this.dislikeCount - 1;
    } else {
      await this.quoteService
        .dislikeUp(id)
        .pipe(takeUntil(this.notifier))
        .subscribe({
          next: (response) => {
            // console.log(response);
          },
          error: (err) => (this.errorMessage = err),
        });
      this.isDisliked = true;
      this.dislikeCount = this.dislikeCount + 1;
    }

    if (this.isLiked) {
      this.isLiked = false;
      this.likeCount = this.likeCount - 1;
    }
    this.setImgSrc();
  };
}

<!-- <pre>{{ quoteItem.quote }}</pre> -->
<!-- <div class="card-container">
  <div class="card">
    <div class="card-header">
      <img class="avatar" src="https://joeschmoe.io/api/v1/random" />
      <div class="info">
        <div class="row">
          <p class="creator">{{ quoteItem.user.userName }}</p>
          <div class="row moment-date"></div>
          {{ quoteItem.user.created_at | amDateFormat: "LL" }}
        </div>
      </div>
    </div>
    <div class="card-body">
      {{ quoteItem.quote }}{{ quoteItem.author }}{{ quoteItem.tags }}
    </div>
    <div class="card-footer" *ngIf="isLoggedIn"></div>
  </div>
</div> -->

<div class="card-container">
  <div class="card">
    <div class="card-header">
      <div class="row">
        <div class="col-md-1 mr-0 pr-0">
          <img class="avatar" src="https://joeschmoe.io/api/v1/random" />
        </div>
        <div class="col-md-3 ml-0 pl-0 info">
          <p class="creator">{{ quoteItem.user.userName }}</p>
          <div class="moment-date">
            {{ quoteItem.user.created_at | amDateFormat: "LL" }}
          </div>
        </div>
      </div>
    </div>
    <div class="card-body">
      <div id="title">"{{ quoteItem.quote }}"</div>
      <div id="author">{{ quoteItem.author }}</div>
      <ul class="tag-list" *ngFor="let item of tags">
        <li>{{ item }}</li>
      </ul>
    </div>
    <div class="card-footer" *ngIf="isLoggedIn">
      <div class="row">
        <div class="col-md-6 icons">
          <img
            src="{{ likeImgSrc }}"
            id="image-icons"
            alt="logo"
            (click)="onClickLike(quoteItem.id)"
          />
          {{ likeCount }}
        </div>
        <div class="col-md-6 icons">
          <img
            src="{{ disLikeImgSrc }}"
            id="image-icons"
            class="dislike-image"
            alt="logo"
            (click)="onClickDislike(quoteItem.id)"
          />
          {{ dislikeCount }}
        </div>
      </div>
    </div>
  </div>
</div>
