// quotes-app/fe-vue/src/components/DisplayQuotes/CardItem.vue
<template>
  <div class="card">
    <div class="card-header">
      <div class="info">
        <p class="creator">{{ userName }}</p>
        <div class="moment-date" format="dddd, MMMM Do YYYY">
          {{ createdAt }}
        </div>
      </div>
    </div>
    <div class="card-body">
      <blockquote class="blockquote mb-0">
        <p class="title">"{{ quote }}"</p>
        <footer class="blockquote-footer">
          <cite class="description" title="Source Title">{{ author }}</cite>
        </footer>
        <ul class="tag-list">
          <li v-for="(tag, index) in separateOutTags" :key="index">
            {{ tag }}
          </li>
        </ul>
      </blockquote>
    </div>
    <div v-if="isUserLoggedIn" class="card-footer">
      <ul class="card-actions">
        <li :style="{ width: cardFooterItemWidth }">
          <img
            v-if="!likeFlag"
            src="../../assets/likeIcons/like-unfilled.jpg"
            id="card-icons"
            alt="logo"
            :onclick="() => onClickLike()"
          />
          <img
            v-if="likeFlag"
            src="../../assets/likeIcons/like-filled.png"
            id="card-icons"
            alt="logo"
            :onclick="() => onClickLike()"
          />
          {{ likeCount }}
        </li>
        <li :style="{ width: cardFooterItemWidth }">
          <img
            v-if="!dislikeFlag"
            src="../../assets/likeIcons/like-unfilled.jpg"
            id="card-icons"
            class="dislike-image"
            alt="logo"
            :onclick="() => onClickDislike()"
          />

          <img
            v-if="dislikeFlag"
            src="../../assets/likeIcons/like-filled.png"
            id="card-icons"
            class="dislike-image"
            alt="logo"
            :onclick="() => onClickDislike()"
          />
          {{ dislikeCount }}
        </li>
        <li v-if="showEditDelete" :style="{ width: cardFooterItemWidth }">
          <EditQuote
            :quoteId="quoteId"
            :quote="quote"
            :author="author"
            :tags="tags"
          />
        </li>
        <li v-if="showEditDelete" :style="{ width: cardFooterItemWidth }">
          <img
            src="../../assets/delete.png"
            id="card-icons"
            alt="logo"
            :onclick="() => onClickDelete()"
          />
        </li>
      </ul>
    </div>
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import moment from "moment";
import { FavQuote } from "@/interfaces/types";
import { helpers } from "@/utils/generalHelpers";
import {
  deleteQuote,
  dislikeDown,
  dislikeUp,
  likeDown,
  likeUp,
} from "@/apis/protectedRoutes";
import { mdiDelete, mdiPencil } from "@mdi/js";
import EditQuote from "@/components/UserDetails/ModalPopup/EditQuote.vue";
import { useUserStore } from "@/stores/userStore";

export default defineComponent({
  name: "CardItem",
  components: { EditQuote },
  props: [
    "quoteId",
    "quote",
    "author",
    "created_at",
    "tags",
    "likes",
    "dislikes",
    "userName",
    "showEditDelete",
  ],
  data() {
    return {
      likeFlag: false,
      dislikeFlag: false,
      likeCount: this.likes,
      dislikeCount: this.dislikes,
      mdiDelete,
      mdiPencil,
      cardFooterItemWidth: this.showEditDelete ? "25%" : "50%",
    };
  },
  methods: {
    setInitialLiked() {
      const likedQuotes = helpers.getLikedQuotes();
      if (likedQuotes.length)
        likedQuotes.forEach((likedQuote: FavQuote) => {
          if (likedQuote.quote.id === this.quoteId) this.likeFlag = true;
        });
    },
    setInitialDisliked() {
      const dislikedQuotes = helpers.getDislikedQuotes();
      if (dislikedQuotes.length)
        dislikedQuotes.forEach((dislikedQuote: FavQuote) => {
          if (dislikedQuote.quote.id === this.quoteId) this.dislikeFlag = true;
        });
    },
    async onClickLike() {
      if (this.likeFlag) {
        await likeDown(this.quoteId);
        this.likeFlag = false;
        this.likeCount -= 1;
      } else {
        await likeUp(this.quoteId);
        this.likeFlag = true;
        this.likeCount += 1;
      }

      if (this.dislikeFlag) {
        this.dislikeFlag = false;
        this.dislikeCount -= 1;
      }
    },
    async onClickDislike() {
      if (this.dislikeFlag) {
        await dislikeDown(this.quoteId);
        this.dislikeFlag = false;
        this.dislikeCount -= 1;
      } else {
        await dislikeUp(this.quoteId);
        this.dislikeFlag = true;
        this.dislikeCount += 1;
      }

      if (this.likeFlag) {
        this.likeFlag = false;
        this.likeCount -= 1;
      }
    },
    async onClickDelete() {
      let result = await helpers.getConfirmAlert({
        title: "Are you sure you want to delete this quote?",
        icon: "info",
        confirmButtonText: "Yes, delete it!",
      });
      if (result.isConfirmed) {
        const response = await deleteQuote(this.quoteId);
        if (response.deleted) {
          const userStore = useUserStore();
          userStore.fetchQuotes();
        }
      }
    },
  },
  computed: {
    createdAt() {
      return moment(this.created_at).format("dddd, MMMM Do YYYY");
    },
    separateOutTags() {
      return this.tags.split(",");
    },
    isUserLoggedIn() {
      const isLoggedIn = helpers.getUserLoggedIn();
      if (isLoggedIn) {
        this.setInitialLiked();
        this.setInitialDisliked();
      }
      return isLoggedIn;
    },
  },
});
</script>

<style scoped>
.title {
  white-space: pre-wrap;
  font-style: italic;
  font-size: 20px;
  /* color: #413939; */
}

.description {
  font-style: italic;
  font-size: 17px;
}

.card {
  margin: auto;
  width: 95%;
  margin-bottom: 0.5em;
}

.icons {
  font-size: 15px;
}

.creator {
  color: #5cb85c;
  font-weight: 500 !important;
}

.dislike-image {
  transform: rotate(180deg);
}

/* .like-dislike-value {
	float: right;
	position: relative;
	right: 7.6rem;
} */

.card-heading {
  display: block;
  position: relative;
  font-weight: 300;
  margin-bottom: 0.6rem;
}

.card-heading .info {
  margin: 0 1.5rem 0 0.6rem;
  display: inline-block;
  vertical-align: middle;
  line-height: 0.7rem;
}

.card-heading .info .moment-date {
  color: #bbb;
  font-size: 0.8rem;
}

ul.tag-list {
  float: right;
  max-width: 50%;
  vertical-align: top;
  margin-bottom: 1rem;
  margin-top: 0.6em;
}

ul.tag-list li {
  display: inline-block !important;
  border: 1px solid #ddd;
  color: #aaa !important;
  background: 0 0 !important;
  font-weight: 300;
  font-size: 0.8rem !important;
  padding-top: 0 !important;
  padding-bottom: 0 !important;
  padding-right: 0.6em;
  padding-left: 0.6em;
  border-radius: 10rem;
  margin-right: 3px;
  margin-bottom: 0.2rem;
  white-space: nowrap;
}

/* .ant-card {
	border-bottom-color: rgb(75, 74, 74);
} */

.card-actions {
  margin: 0;
  padding: 0;
  list-style: none;
  border-top: 1px solid #f0f0f0;
}

ul.card-actions li {
  float: left;
  margin: 12px 0;
  color: rgba(0, 0, 0, 0.45);
  text-align: center;
}

.card-actions > li:not(:last-child) {
  border-right: 1px solid #dfd4d4;
}

.card:hover {
  cursor: pointer;
  border-color: transparent;
  box-shadow: 0 1px 2px -2px rgba(0, 0, 0, 0.16),
    0 3px 6px 0 rgba(0, 0, 0, 0.12), 0 5px 12px 4px rgba(0, 0, 0, 0.09);
}
</style>

// quotes-app/fe-ts-react/src/components/cardItem/cardItem.tsx
import "./cardItem.css";
import { Card, Tooltip } from "antd";
import Moment from "react-moment";
import { EditTwoTone, DeleteTwoTone } from "@ant-design/icons";
import { useEffect, useState } from "react";
import Avatar from "antd/lib/avatar/avatar";
import { auth } from "../../utils/authHelpers";
import {
	deleteQuote,
	dislikeDown,
	dislikeUp,
	likeDown,
	likeUp,
} from "../../apis/protectedRoutes";
import { EditModal } from "../modals/editQuote";
import { helpers } from "../../utils/generalHelpers";
import { EditQuoteDetailed, QuoteDetailed } from "../../interfaces/types";

const swalProps = {
	title: "Are you sure you want to delete this quote ?",
	icon: "info",
	confirmButtonText: "Yes, delete it!",
};

export interface CardItemProps {
	key: string;
	loading: boolean;
	item: QuoteDetailed;
	isLiked: boolean;
	isDisliked: boolean;
	myQuotes: boolean;
	fetchMyQuotes: () => void;
}

const { Meta } = Card;

export const CardItem = (props: CardItemProps) => {
	const [isEditModalVisible, setIsEditModalVisible] = useState(false);
	const [editModalData, setEditModalData] = useState<EditQuoteDetailed>({});
	const [isLoggerIn, setIsLoggerIn] = useState<boolean>(auth.isLoggedIn());
	const [isLiked, setIsLiked] = useState(false);
	const [isDisliked, setIsDisliked] = useState(false);
	const [likeCount, setLikeCount] = useState(props.item.likes);
	const [dislikeCount, setDislikeCount] = useState(props.item.dislikes);

	useEffect(() => {
		if (props.isLiked) setIsLiked(true);

		if (props.isDisliked) setIsDisliked(true);
	}, [props]);

	const onClickEdit = (item: QuoteDetailed) => {
		setEditModalData(item);
		setIsEditModalVisible(true);
	};

	const handleEditModalCancel = () => {
		setIsEditModalVisible(false);
		props.fetchMyQuotes();
	};

	const onClickDelete = async (id: string) => {
		let result = await helpers.getConfirmAlert({ ...swalProps });
		if (result.isConfirmed) {
			await deleteQuote(id);
			props.fetchMyQuotes();
		}
	};

	const onClickLike = async (id: string) => {
		if (isLiked) {
			await likeDown(id);
			setIsLiked(false);
			setLikeCount(likeCount - 1);
		} else {
			await likeUp(id);
			setIsLiked(true);
			setLikeCount(likeCount + 1);
		}

		if (isDisliked) {
			setIsDisliked(false);
			setDislikeCount(dislikeCount - 1);
		}
	};

	const onClickDislike = async (id: string) => {
		if (isDisliked) {
			await dislikeDown(id);
			setIsDisliked(false);
			setDislikeCount(dislikeCount - 1);
		} else {
			await dislikeUp(id);
			setIsDisliked(true);
			setDislikeCount(dislikeCount + 1);
		}

		if (isLiked) {
			setIsLiked(false);
			setLikeCount(likeCount - 1);
		}
	};

	const getLikeIcon = () => {
		return (
			<>
				{isLiked ? (
					<img
						src={"/like-filled.png"}
						id="image-icons"
						alt="logo"
						onClick={() => onClickLike(props.item.id)}
					/>
				) : (
					<img
						src={"/like-unfilled.jpg"}
						id="image-icons"
						alt="logo"
						onClick={() => onClickLike(props.item.id)}
					/>
				)}
			</>
		);
	};

	const getDislikeIcon = () => {
		return (
			<>
				{isDisliked ? (
					<img
						src={"/like-filled.png"}
						id="image-icons"
						className="dislike-image"
						alt="logo"
						onClick={() => onClickDislike(props.item.id)}
					/>
				) : (
					<img
						src={"/like-unfilled.jpg"}
						id="image-icons"
						className="dislike-image"
						alt="logo"
						onClick={() => onClickDislike(props.item.id)}
					/>
				)}
			</>
		);
	};

	const getActions = () => {
		const actions = [];
		if (isLoggerIn) {
			actions.push(
				<div>
					<div className="like-dislike-value">
						{getLikeIcon()} {likeCount}
					</div>
				</div>,
				<div>
					<div className="like-dislike-value">
						{getDislikeIcon()} {dislikeCount}
					</div>
				</div>
			);

			if (props.myQuotes)
				actions.push(
					<div>
						<Tooltip title="Edit">
							<EditTwoTone
								className="icons"
								twoToneColor="#413939"
								key="edit"
								onClick={() => onClickEdit(props.item)}
							/>
						</Tooltip>
					</div>,
					<div>
						<Tooltip title="Delete">
							<DeleteTwoTone
								className="icons"
								twoToneColor="#eb2f96"
								onClick={() => onClickDelete(props.item.id)}
							/>
						</Tooltip>
					</div>
				);
		}
		return actions;
	};

	return (
		<div className="card-container">
			{isEditModalVisible && (
				<EditModal
					isEditModalVisible={isEditModalVisible}
					handleEditModalCancel={handleEditModalCancel}
					data={editModalData}
				/>
			)}
			<Card
				key={props.item.id}
				loading={props.loading}
				hoverable={true}
				bordered={true}
				// style={{
				// 	backgroundColor: "#c59ec0",
				// }}
				// bodyStyle={{
				// 	textAlign: "center",
				// 	// wordWrap: "break-word",
				// 	whiteSpace: "pre-line",
				// }}
				actions={getActions()}
			>
				<div className="card-heading">
					<Avatar src="https://joeschmoe.io/api/v1/random" />
					<div className="info">
						<p className="creator"> {props.item.user.userName}</p>
						<Moment className="moment-date" format="dddd, MMMM Do YYYY">
							{props.item.created_at}
						</Moment>
					</div>
				</div>
				<Meta
					title={'"' + props.item.quote + '"'}
					description={props.item.author}
					style={{ textAlign: "center", whiteSpace: "pre-line" }}
				/>
				<ul className="tag-list">
					{props.item.tags.split(",").map((tag, index) => (
						<li key={index}>{tag}</li>
					))}
				</ul>
			</Card>
		</div>
	);
};
